global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'FID'
    scrape_interval: 5m
    scrape_timeout: 30s
    static_configs:
      - targets: ['fid-bff:5000', 'scheme-manager:3333']
  
  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']